name: Deploy INVOICE

on:
  push:
    branches:
      - ok1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy ke VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/invoice

            git fetch origin
            git reset --hard origin/ok1

            php artisan optimize:clear
            php artisan optimize


